# Generated by Selenium IDE + 디버거 크롬

import chromedriver_autoinstaller
import subprocess
import shutil
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options

# import pytest
# import time
# import json
# from selenium.webdriver.common.action_chains import ActionChains
# from selenium.webdriver.support import expected_conditions
# from selenium.webdriver.support.wait import WebDriverWait
# from selenium.webdriver.common.keys import Keys
# from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestTry1():

    try:
        shutil.rmtree(r"c:\chrometemp")  #쿠키 / 캐쉬파일 삭제
        print("try1")
    except FileNotFoundError:
        pass

    subprocess.Popen(r'C:\Program Files\Google\Chrome\Application\chrome.exe --remote-debugging-port=9222 --user-data-dir="C:\chrometemp"') # 디버거 크롬 구동


    option = Options()
    option.add_experimental_option("debuggerAddress", "127.0.0.1:9222")

    chrome_ver = chromedriver_autoinstaller.get_chrome_version().split('.')[0]

    try:
        driver = webdriver.Chrome(f'../chromedriver.exe', options=option)
        print("try2")
    except:
        chromedriver_autoinstaller.install(True)
        driver = webdriver.Chrome(f'../chromedriver.exe', options=option)
        driver.implicitly_wait(10) 

    driver = webdriver.Chrome()
    vars = {}


    def test_try1(self):

        # 반복문으로 iplist파일(gitignore)의 데이터 돌릴 예정
        iplist='178.175.119.165'

        self.driver.get("https://ipremoval.sms.symantec.com/")
        # self.driver.set_window_size(1651, 1032)
        self.driver.find_element(By.CSS_SELECTOR,'#ip').send_keys(self.vars[iplist])
        self.driver.switch_to.frame(0)
        self.driver.find_element(By.CSS_SELECTOR, ".recaptcha-checkbox-border").click()
        self.driver.switch_to.default_content()
        self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(10)").click()

        FIRST = self.driver.find_element(By.XPATH, '//*[@id="ContentBox"]/p')
        SECOND = self.driver.find_element(By.XPATH, '//*[@id="ContentBox"]/ul')
        return(FIRST, "\n", SECOND)


Test1 = TestTry1()
Test1.test_try1()
print("try3")

