# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTry1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_try1(self):

    iplist='178.175.119.165'

    self.driver.get("https://ipremoval.sms.symantec.com/")
    self.driver.set_window_size(1651, 1032)
    self.driver.find_element(By.ID, "ip").click()
    self.driver.find_element(By.ID, "ip").click()
    self.driver.find_element(By.ID, "ip").send_keys(self.vars[iplist])
    self.driver.switch_to.frame(0)
    self.driver.find_element(By.CSS_SELECTOR, ".recaptcha-checkbox-border").click()
    self.driver.switch_to.default_content()
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(10)").click()
    FIRST = self.driver.find_element(By.XPATH, '//*[@id="ContentBox"]/p')
    SECOND = self.driver.find_element(By.XPATH, '//*[@id="ContentBox"]/ul')
    print(FIRST)
    print(SECOND)
